import 'package:card_crawler/provider/gameplay/model/game_card.dart';

import '../../type/effect/monster_effect.dart';
import '../../type/game_card_type.dart';

String _spritePath(String fileName) => 'assets/card_sprites/monsters/$fileName';

List<GameCard> monsterGameCards = [
  GameCard(
    id: 23,
    type: GameCardType.monster,
    value: 2,
    effect: Sticky(),
    asset: _spritePath('2_1.png'),
  ),
  GameCard(
    id: 24,
    type: GameCardType.monster,
    value: 2,
    effect: Sticky(),
    asset: _spritePath('2_2.png'),
  ),
  GameCard(
    id: 25,
    type: GameCardType.monster,
    value: 3,
    effect: Corrosive(),
    asset: _spritePath('3_1.png'),
  ),
  GameCard(
    id: 26,
    type: GameCardType.monster,
    value: 3,
    effect: Corrosive(),
    asset: _spritePath('3_2.png'),
  ),
  GameCard(
    id: 27,
    type: GameCardType.monster,
    value: 4,
    effect: Ally(),
    asset: _spritePath('4_1.png'),
  ),
  GameCard(
    id: 28,
    type: GameCardType.monster,
    value: 4,
    effect: Ally(),
    asset: _spritePath('4_2.png'),
  ),
  GameCard(
    id: 29,
    type: GameCardType.monster,
    value: 5,
    effect: Scaling(),
    asset: _spritePath('5_1.png'),
  ),
  GameCard(
    id: 30,
    type: GameCardType.monster,
    value: 5,
    effect: Scaling(),
    asset: _spritePath('5_2.png'),
  ),
  GameCard(
    id: 31,
    type: GameCardType.monster,
    value: 6,
    effect: Aftermath(),
    asset: _spritePath('6_1.png'),
  ),
  GameCard(
    id: 32,
    type: GameCardType.monster,
    value: 6,
    effect: Aftermath(),
    asset: _spritePath('6_2.png'),
  ),
  GameCard(
    id: 33,
    type: GameCardType.monster,
    value: 7,
    effect: Poisonous(),
    asset: _spritePath('7_1.png'),
  ),
  GameCard(
    id: 34,
    type: GameCardType.monster,
    value: 7,
    effect: Poisonous(),
    asset: _spritePath('7_2.png'),
  ),
  GameCard(
    id: 35,
    type: GameCardType.monster,
    value: 8,
    effect: Mimic(),
    asset: _spritePath('8_1.png'),
  ),
  GameCard(
    id: 36,
    type: GameCardType.monster,
    value: 8,
    effect: Mimic(),
    asset: _spritePath('8_2.png'),
  ),
  GameCard(
    id: 37,
    type: GameCardType.monster,
    value: 9,
    effect: Vengeful(),
    asset: _spritePath('9_1.png'),
  ),
  GameCard(
    id: 38,
    type: GameCardType.monster,
    value: 9,
    effect: Vengeful(),
    asset: _spritePath('9_2.png'),
  ),
  GameCard(
    id: 39,
    type: GameCardType.monster,
    value: 10,
    effect: Opportunist(),
    asset: _spritePath('10_1.png'),
  ),
  GameCard(
    id: 40,
    type: GameCardType.monster,
    value: 10,
    effect: Opportunist(),
    asset: _spritePath('10_2.png'),
  ),
  GameCard(
    id: 41,
    type: GameCardType.monster,
    value: 11,
    effect: Wrecker(),
    asset: _spritePath('11_1.png'),
  ),
  GameCard(
    id: 42,
    type: GameCardType.monster,
    value: 11,
    effect: Wrecker(),
    asset: _spritePath('11_2.png'),
  ),
  GameCard(
    id: 43,
    type: GameCardType.monster,
    value: 12,
    effect: Spiky(),
    asset: _spritePath('12_1.png'),
  ),
  GameCard(
    id: 44,
    type: GameCardType.monster,
    value: 12,
    effect: Spiky(),
    asset: _spritePath('12_2.png'),
  ),
  GameCard(
    id: 45,
    type: GameCardType.monster,
    value: 13,
    effect: AntiHeal(),
    asset: _spritePath('13_1.png'),
  ),
  GameCard(
    id: 46,
    type: GameCardType.monster,
    value: 13,
    effect: AntiHeal(),
    asset: _spritePath('13_2.png'),
  ),
  GameCard(
    id: 47,
    type: GameCardType.monster,
    value: 14,
    effect: NoEscape(),
    asset: _spritePath('14_1.png'),
  ),
  GameCard(
    id: 48,
    type: GameCardType.monster,
    value: 14,
    effect: NoEscape(),
    asset: _spritePath('14_2.png'),
  ),
];
